---
image: docker:18.01.0-ce-git
services:
  - docker:18.01.0-ce-dind
stages:
  - build
  - deploy

variables:
  DJANGO_RELEASE_IMAGE: $CI_REGISTRY_IMAGE/django:$CI_BUILD_REF_NAME
  NGINX_RELEASE_IMAGE: $CI_REGISTRY_IMAGE/nginx:$CI_BUILD_REF_NAME
  POSTGRES_RELEASE_IMAGE: $CI_REGISTRY_IMAGE/postgres:$CI_BUILD_REF_NAME

#############
## Production
#############
build to production:
  stage: build
  script:
    - docker login -u "gitlab-ci-token" -p "$CI_JOB_TOKEN" $CI_REGISTRY
    - docker build -f compose/production/Dockerfile --target django -t $DJANGO_RELEASE_IMAGE .
    - docker tag $DJANGO_RELEASE_IMAGE "$CI_REGISTRY_IMAGE/django:latest"
    - docker push $DJANGO_RELEASE_IMAGE
    - docker push "$CI_REGISTRY_IMAGE/django:latest"
    - docker build -f compose/production/Dockerfile --target nginx -t $NGINX_RELEASE_IMAGE .
    - docker tag $NGINX_RELEASE_IMAGE "$CI_REGISTRY_IMAGE/nginx:latest"
    - docker push $NGINX_RELEASE_IMAGE
    - docker push "$CI_REGISTRY_IMAGE/nginx:latest"
    - docker build -f compose/production/postgres/Dockerfile -t $POSTGRES_RELEASE_IMAGE .
    - docker tag $POSTGRES_RELEASE_IMAGE "$CI_REGISTRY_IMAGE/postgres:latest"
    - docker push $POSTGRES_RELEASE_IMAGE
    - docker push "$CI_REGISTRY_IMAGE/postgres:latest"
  only:
    - tags
  environment: production
  tags:
    - docker

# deploy to production:
#   stage: deploy
#   image: cdrx/rancher-gitlab-deploy
#   script:
#     - upgrade --environment <env_name> --stack <stack_name> --service <service_name> --no-finish-upgrade --sidekicks
#   only:
#     - tags
#   environment: production
#   tags:
#     - docker

##########
## Homolog
##########
build to homolog:
  stage: build
  script:
    - docker login -u "gitlab-ci-token" -p "$CI_JOB_TOKEN" $CI_REGISTRY
    - docker build -f compose/production/Dockerfile --target django -t $DJANGO_RELEASE_IMAGE .
    - docker push $DJANGO_RELEASE_IMAGE
    - docker build -f compose/production/Dockerfile --target nginx -t $NGINX_RELEASE_IMAGE .
    - docker push $NGINX_RELEASE_IMAGE
    - docker build -f compose/production/postgres/Dockerfile -t $POSTGRES_RELEASE_IMAGE .
    - docker push $POSTGRES_RELEASE_IMAGE
  only:
    - /master/
  environment: homolog
  tags:
    - docker

deploy to homolog:
  stage: deploy
  image: cdrx/rancher-gitlab-deploy
  script:
    - upgrade --environment IMS --stack guia-ims-dev --service backend --no-finish-upgrade --sidekicks
  only:
    - /master/
  environment: homolog
  tags:
    - docker
