version: '3.6'

services:
  redis:
    image: redis:3.2
    hostname: redis

  django:
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    depends_on:
      - postgres
    volumes:
      - .:/app
    environment:
      - DB_NAME=django
      - DB_USER=django
      - DB_PASSWORD=django
      - DEBUG=False
      - DEFAULT_FROM_EMAIL=no-replay@ims.com.br
      - EMAIL_HOST=smtp.server.com
      - EMAIL_PORT=587
      - EMAIL_HOST_USER=user@ims.com.br
      - EMAIL_HOST_PASSWORD=my-password
      - EMAIL_USE_TLS=True
      - BASE_URL=http://0.0.0.0:8000
    ports:
      - "8000:8000"
    command: /runserver.sh

  postgres:
    build:
      context: .
      dockerfile: ./compose/local/postgres/Dockerfile
    volumes:
      - ./db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=django
      - POSTGRES_USER=django
      - POSTGRES_PASSWORD=django
